# Generated by Django 4.0.6 on 2022-08-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
